server:
  port: 8888

spring:
  application:
    name: lift
  datasource:
    url: jdbc:mysql://120.77.252.112:3306/lift?serverTimezone=GMT%2B8
    username: root
    password: gexiao
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 16
      max-wait: 60000
      keep-alive: true
      validation-query: select 1
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  servlet:
    # 上传文件大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    # 资源路径设置
    static-path-pattern: /upload/**
  resources:
    # 资源路径设置
    static-locations: classpath:upload/,upload/,file:upload/

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      # 该策略约定了如何产出注入的sql,涉及insert,update以及wrapper内部的entity属性生成的 where 条件（空字符串或空都将去掉）
      field-strategy: NOT_EMPTY

# 打印sql
logging:
  level:
    com.gexiao.demo.dao : debug

# 网关参数
gateway:
  # 不校验的uri
  unchecked:
    - /user/login
    - /user/
    - /user/logout

# 设置分页插件
pagehelper:
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
  page-size-zero: true
